# -*- coding: utf-8 -*-
"""GHGbyFoodGroups.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SZJVVmSw-s0QaFKfjMKe17BAgU3ZiDR4
"""

! pip install PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

data = drive.CreateFile({'id':"1CV6q23h2LUMIB-625SK8nwNxNHokPUhs"})
data.GetContentFile("GHG avg by food groups.xlsx")

!pip install -q xlrd
import pandas as pd

# Load file in dataframe format
df_plant_starches = pd.read_excel("GHG avg by food groups.xlsx","Plant starches")
df_plant_proteins = pd.read_excel("GHG avg by food groups.xlsx","Plant proteins")
df_animal_proteins = pd.read_excel("GHG avg by food groups.xlsx","Animal proteins")
df_vegetables = pd.read_excel("GHG avg by food groups.xlsx","Vegetables")
df_fruits = pd.read_excel("GHG avg by food groups.xlsx","Fruits")
df_plant_oils = pd.read_excel("GHG avg by food groups.xlsx","Plant oils")
df_dairy = pd.read_excel("GHG avg by food groups.xlsx","Dairy")
df_mis = pd.read_excel("GHG avg by food groups.xlsx","Miscellaneous")

# Concatenate the frames
frames = [df_plant_starches,df_plant_proteins,df_animal_proteins,df_vegetables,df_fruits,df_plant_oils,df_dairy,df_mis]
df = pd.concat(frames)

df.head()

avg_ghg = df.pop('Avg GHG (kg CO2 equivalent/ kg product)')

df.tail()

# Get average GHG by Food groups
grouped_df = df.groupby(by=['Food group']).mean()
grouped_df = grouped_df.sort_values(by = 'Total GHG (kg CO2 equivalent/ kg product)', ascending = False)
grouped_df

# Create bar chart for Total GHG by food group
rm_total = grouped_df.pop('Total GHG (kg CO2 equivalent/ kg product)')
new_grouped_df = grouped_df
new_grouped_df.plot.bar(stacked = True)

for df in frames:
  new_df = df[['Food product','Land use change', 'Animal Feed', 'Farm', 'Processing', 'Transport',
       'Packging', 'Retail']]
  new_df = new_df.set_index('Food product')
  ax = new_df.plot.bar(stacked = True)